# Generated by Django 5.0.4 on 2024-07-10 09:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bot_User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tg_id', models.SlugField(unique=True)),
                ('first_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(max_length=120)),
                ('tg_full_name', models.CharField(max_length=120)),
                ('tg_username', models.CharField(blank=True, max_length=120, null=True)),
                ('region', models.CharField(max_length=120)),
                ('district', models.CharField(max_length=120)),
                ('phone_number', models.CharField(max_length=13)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_ban', models.BooleanField(default=False)),
                ('is_admin', models.CharField(default='A', max_length=2)),
            ],
            options={
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='Joylinks_Courses',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('info', models.TextField(blank=True, null=True)),
                ('photo', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User_Enroll_Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_state', models.IntegerField(default=0, max_length=1)),
                ('off_state', models.IntegerField(default=0, max_length=1)),
                ('course_id', models.ManyToManyField(to='users_app.joylinks_courses')),
                ('tg_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users_app.bot_user')),
            ],
        ),
    ]
